let list = [
    {
      id: 1,
      title: "One piece",
      author: "Eiichirō Oda",
      price: 7,
      img: "https://www.slumberlandbdworld.com/55343-large_default/one-piece-edition-originale-tome-01.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Naruto",
      author: "Masashi Kishimoto",
      price: 7,
      img: "https://www.pro-bems.com/IMAGES/images_1/NARUTO89201AS/g/NARUTO89201AS_1.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Dragon Ball",
      author: "Akira Toriyama",
      price: 7,
      img: "https://static.fnac-static.com/multimedia/Images/FR/NR/00/ed/4d/5106944/1540-1/tsp20230101065302/Dragon-Ball-Edition-originale.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Saint Seiya",
      author: "Masami Kurumada",
      price: 7,
      img: "https://static.fnac-static.com/multimedia/Images/FR/NR/f2/ec/02/191730/1540-1/tsp20210304165441/Chevaliers-du-zodiaque.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Kingdom",
      author: "Yasuhisa Hara",
      price: 8,
      img: "https://img.livraddict.com/covers/295/295576//couv20709122.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "My heros Academia",
      author: "Kōhei Horikoshi",
      price: 7,
      img: "https://static.fnac-static.com/multimedia/Images/FR/NR/5e/3c/d2/13778014/1507-1/tsp20210906114206/My-Hero-Academia.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Shingeki No kyojin",
      author: "Hajime Isayama",
      price: 8,
      img: "https://static.fnac-static.com/multimedia/Images/FR/NR/89/cf/4a/4902793/1540-1/tsp20220625095705/L-Attaque-des-Titans.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Hunter x hunter",
      author: "Yoshihiro Togashi",
      price: 7,
      img: "https://images-eu.ssl-images-amazon.com/images/I/81kn7-YrYBL._AC_UL600_SR600,400_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Chainsaw-man",
      author: "Tatsuki Fujimoto",
      price: 8,
      img: "https://static.fnac-static.com/multimedia/Images/FR/NR/9e/64/b1/11625630/1540-1/tsp20221005072742/Chainsaw-Man.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Haikyuu",
      author: "Haruichi Furudate",
      price: 7,
      img: "https://m.media-amazon.com/images/I/81zvggjBliL.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Jujutsu Kaisen",
      author: "Gege Akutami",
      price: 7,
      img: "https://www.manga-news.com/public/images/series/Jujutsu-Kaisen-1-ki-oon.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Origin",
      author: " Boichi",
      price: 9,
      img: "https://www.manga-news.com/public/images/series/origin-1-pika.jpg",
      amount: 1,
    },
];

export default list;